export const EXPERIENCE_DATA = {
  header: {
    title: "Professional Experience",
    subtitle:
      "3+ years of expertise in Java, Spring Boot, and full-stack development.",
  },
  roles: [
    {
      title: "Junior Software Developer",
      company: "Memob Plus Pvt Ltd",
      duration: "April 2023 – Present",
      location: "Chennai, Tamil Nadu",
      responsibilities: [
        "Designed and developed scalable <strong>microservices</strong> using <strong>Java</strong> and <strong>Spring Boot</strong>, exposing RESTful APIs with a focus on low latency.",
        "Cut API latency by <strong>20%</strong> by implementing a targeted <strong>Redis</strong> caching strategy for background tasks.",
        "Improved database performance by <strong>10%</strong> through strategic indexing and advanced <strong>PostgreSQL</strong> query optimization.",
        "Contributed to the modernization of a legacy system, enhancing the UI with <strong>Next.js</strong>.",
        "Architected a unified audience management service to integrate with marketing platforms like <strong>Meta, Snapchat, and Tik Tok</strong>.",
      ],
      techStack: [
        "Java",
        "Spring Boot",
        "Microservices",
        "Redis",
        "RabbitMQ",
        "Next.js",
        "MUI",
        "PostgreSQL",
        "OAuth 2.0",
      ],
    },
    {
      title: "Software Developer Trainee",
      company: "Memob Plus Pvt Ltd",
      duration: "Aug 2022 – April 2023",
      location: "Chennai, Tamil Nadu",
      responsibilities: [
        "Created a special <strong>proximity hash</strong> in <strong>Java</strong> for better location-based targeting, improving accuracy by <strong>15%</strong>.",
        "Optimized database queries using <strong>PostgreSQL</strong> to enhance data retrieval speed and improve application performance.",
      ],
      techStack: [
        "Java",
        "Spring Boot",
        "React.js",
        "Mapbox",
        "RabbitMQ",
        "PostgreSQL",
        "Redis",
        "MUI",
      ],
    },
  ],
  achievements: [
    "Cut API latency by <strong>20%</strong> through <strong>Redis</strong> caching strategies.",
    "Improved database performance by <strong>10%</strong> using <strong>PostgreSQL</strong> indexing and query optimization.",
    "Enhanced geospatial targeting accuracy by <strong>15%</strong> with a custom Java proximity hash algorithm.",
  ],
  skills: [
    "Java",
    "Spring Boot",
    "Microservices",
    "RESTful APIs",
    "Hibernate",
    "Redis",
    "RabbitMQ",
    "PostgreSQL",
    "JavaScript",
    "Next.js",
  ],
};